Translate the "About" page to Arabic and update team-related sections
vuejs-translations/docs-ar pull request #165
Opened 2024-08-31 19:18 UTC by anisharkat

## Description of what I did:

Translate the "About" page to Arabic and update team-related sections 👍

2024-08-31 22:39 UTC, Abdelaziz18003 requested changes

2024-08-31 22:39 UTC, Abdelaziz18003 commented on pnpm-lock.yaml
تجنب تضمين هذا الملف في ال commit، الرجاء تضمين الصفحات المترجمة فقط

2024-09-01 02:34 UTC, anisharkat commented
لقد قمت بحذف الملف

2024-09-03 14:55 UTC, Abdelaziz18003 commented
عفوا @anisharkat ربما لم يبلغك قصدي جيدا، لم أقصد حذف الملف نهائيا، وإنما قصدت حذف التغييرات التي طرأت عليه من جانبك اذ ليس لها علاقة بالمحتوى المترجم، إذا واجهتك مشكلة في ذلك يمكنك نسخ هذا الملف من الفرع الرئيسي "main" ولصقه مرة أخرى عندك، أضف "commit" جديدة وأرسل التغييرات مرة أخرى

2024-09-04 00:42 UTC, anisharkat commented
شكرًا على التوضيح. لقد قمت بنسخ الملف من الفرع الرئيسي 'main' وأضفت 'commit' جديدة. تم إرسال التغييرات بنجاح.

2024-09-06 20:21 UTC, Abdelaziz18003 approved these changes

2024-09-06 20:21 UTC, merged